# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [11]:
s="Hi there Sam!"
x=s.split()
x

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [12]:
planet = "Earth"
diameter = 12742
s = "The diameter of {} is {} kilometers."
print(s.format(planet,diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [9]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [8]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]} 
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [10]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [7]:
import numpy as np
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
import numpy as np
b=np.ones(10)*5
print(b)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [5]:
import numpy as np
a=np.arange(20,35,2)
print(a)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
import numpy as np
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [3]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
x=np.concatenate((a,b),axis=None)
print(x)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [13]:
import pandas as pd
data={'Name':['Binushya','Aruna','Deepa'],'Age':['08','06','09']}
a=pd.DataFrame(data)
print(a)

       Name Age
0  Binushya  08
1     Aruna  06
2     Deepa  09


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [2]:
import datetime
import pandas as pd
test = datetime.datetime.strptime("01/01/2023","%d/%m/%Y")
k=41
dg = pd.date_range(test,periods=k)
print(dg.strftime("%d/%m/%y"))

Index(['01/01/23', '02/01/23', '03/01/23', '04/01/23', '05/01/23', '06/01/23',
       '07/01/23', '08/01/23', '09/01/23', '10/01/23', '11/01/23', '12/01/23',
       '13/01/23', '14/01/23', '15/01/23', '16/01/23', '17/01/23', '18/01/23',
       '19/01/23', '20/01/23', '21/01/23', '22/01/23', '23/01/23', '24/01/23',
       '25/01/23', '26/01/23', '27/01/23', '28/01/23', '29/01/23', '30/01/23',
       '31/01/23', '01/02/23', '02/02/23', '03/02/23', '04/02/23', '05/02/23',
       '06/02/23', '07/02/23', '08/02/23', '09/02/23', '10/02/23'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [1]:
import pandas as pd
lists =[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
a = pd.DataFrame(lists,columns=['No','Letter','Numbers'])
print(a)

   No Letter  Numbers
0   1    aaa       22
1   2    bbb       25
2   3    ccc       24
